---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: install git, wget, tree into all nodes
      apt:
       name: "{{ item}}"
       state: present
      with_items: 
       - git
       - wget
       - tree 
