---
- hosts: webservers
  become: yes
  tasks:
    - name: install java on ubntu20 node1
      apt:
       name: "{{ myjavaonubuntu20 }}"
       state: present
      when: ansible_os_family == "Debian" 

    - name: install java on amazonlinux2 node2
      yum: 
       name: "{{ myjavaonamazonlinux2 }}" 
       state: present  
      when: ansible_os_family == "RedHat" 