---
- hosts: webservers
  become: yes
  tasks:
    - name: install java11 on ubuntu20 node1
      apt:
       name: "{{myjavaonubuntu}}"
       state: present
      when: ansible_os_family == "Debian"

    - name: install jdk8 on amazonlinux2 node2
      yum:
       name: "{{myjavaonamzonos}}"
       state: present
       when: ansible_os_family == "Redhat"    