---
- hosts: webservers
  become: yes
  tasks:
    - name: install java on ubuntu20 node1
      apt:
       name: "{{myjavaonubuntu}}"
       state: present
      when: ansible_os_family == "Debian" 

    - name: install java on amazonlinux2 node2
      yum: 
       name: "{{myjavaonamazonos}}" 
       state: present  
      when: ansible_os_family == "RedHat" 