---
- hosts: ubuntuos
  become: yes
  tasks:
  - name: install git 
    apt:
      name: git 
      state: present
    tags: f1

  - name: install wget    
    apt: 
      name: wget
      state: present
    tags: f2

  - name: install tree
    apt:
      name: tree
      state: present
    tags: f3