---
- hosts: all
  become: yes
  tasks:
    - name: install webserver(apache2) on ubuntu20 nodes
      apt:
       name: apache2
       state: present

    - name: start the apache2 service
      service: 
       name: apache2
       state: present    